version: '3'

volumes:
  db_data: {}


services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000